services:

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  backend:
#    build: ./  # Сборка backend-контейнера из образа.
    image: akolmychek/test_proj:latest
    env_file: .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - 8099:80
    volumes:
      - static_volume:/var/html/static
      - media_volume:/var/html/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume: