services:

  backend:
    image: akolmychek/test_proj:latest
    volumes:
      - static_volume:/app/backend_static
      - media_volume:/app/media
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "8099:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/html/static
      - media_volume:/var/html/media
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
